POST http://localhost:3000/api/setup
Content-Type: application/json

{
  "name": "Prashant",
  "balance": 10.0258
}

###
POST http://localhost:3000/api/transact/610e81468acdad0ee080c4c0
Content-Type: application/json

{
  "amount": 10,
  "description": "Salary"
}

###
GET http://localhost:3000/api/transactions/610e81468acdad0ee080c4c0?skip=5&limit=10&order=asc

###
GET http://localhost:3000/api/wallet/610e81468acdad0ee080c4c0
