POST http://localhost:3000/api/setup
Content-Type: application/json

{
  "name": "Prashant",
  "balance": 1000
}

###
POST http://localhost:3000/api/transact/61112948b354ed4c583af9c8
Content-Type: application/json

{
  "amount": 300,
  "description": "Zomato"
}

###
GET http://localhost:3000/api/transactions/61112948b354ed4c583af9c8?limit=10&order=asc

###
GET http://localhost:3000/api/wallet/61112948b354ed4c583af9c8
